mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("pollsApp.urls")),        # include allows referencing other URLconfs
    path('admin/', admin.site.urls),
]

mysite/pollsApp/urls.py
# File created anew, this file is a URLconf which is the way to get Django know about how to display urls. URLconf maps URL patterns to views

from django.urls import path
from . import views

app_name = 'pollsApp'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='details'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

# Previously, in the urlpatterns
    # # ex: /pollsApp/
    # path("", views.index, name='index'),
    # # ex: /pollsApp/5/
    # path('specifics/<int:question_id>/', views.detail, name='detail'),        # the 'name' value is called by the {% url %} template tag
    # # ex: /pollsApp/5/results/
    # path('<int:question_id>/results/', views.results, name='results'),
    # #ex: /pollsApp/5/vote/
    # path('<int:question_id>/vote/', views.vote, name='vote'),

mysite/pollsApp/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib import admin

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=300)
    pub_date = models.DateTimeField("date published")
    # - - -
    def __str__(self) -> str:
        return self.question_text
    @admin.display(
            boolean=True,
            ordering='pub_date',
            description='Published recently?'
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
        # Before the bug was fixed
        # return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    # - - -
    def __str__(self) -> str:
        return self.choice_text

mysite/pollsApp/views.py
# from django.http import Http404

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Question, Choice


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'
    # - - -
    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be published in the future)
        """
        # returns a queryset containing Questions whose pub_date is less then or equeal to timezone.now
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

        ## Previously on this function
        # """Return the last five published questions"""
        # return Question.objects.order_by('-pub_date')[:5]
    
class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/details.html'
    # - - -
    def get_queryset(self):
        """
        Excludes any question that aren't published yet
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/details.html', {
            'question': question,
            'error_message': "You didn't select a choice!",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing with POST data.
        # This prevents data from being posted twice if a user hits the Back button
        return HttpResponseRedirect(reverse('pollsApp:results', args=(question.id,)))




# ### Previously, here, before using the generic views system

# # Create your views here.
# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {
#         'latest_question_list': latest_question_list,
#     }
#     return render(request, 'polls/index.html', context)

# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/details.html', {'question': question})
#     # try:
#     #     question = Question.objects.get(pk=question_id)
#     # except Question.DoesNotExist:
#     #     raise Http404("Question does not exists")
#     # return render(request, 'polls/index.html', {'question': question})

# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html', {'question': question})

# def vote(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     try:
#         selected_choice = question.choice_set.get(pk=request.POST['choice'])
#     except (KeyError, Choice.DoesNotExist):
#         return render(request, 'polls/detail.html', {
#             'question': question,
#             'error_message': "You didn't select a choice!",
#         })
#     else:
#         selected_choice.votes += 1
#         selected_choice.save()
#         # Always return an HttpResponseRedirect after successfully dealing with POST data.
#         # This prevents data from being posted twice if a user hits the Back button
#         return HttpResponseRedirect(reverse('pollsApp:results', args=(question.id,)))

mysite/pollsApp/templates/polls/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Templates Polls Detail</title>
</head>
<body>
    <!-- post method is mandatory whenever creating a form that altes data server-side (it's a general basic concept, not only Django's) -->
    <form action="{% url 'pollsApp:vote' question.id %}" method="post">
        <!-- used to solve the Cross Site Request Forgeries -->
        {% csrf_token %} 
        <fieldset>
            <legend><h1>{{ question.question_text }}</h1></legend>
            {% if error_message %}
                <p><strong>{{ error_message }}</strong></p>
            {% endif %}
            {% for choice in question.choice_set.all %} 
                <!-- radio button for each choice -->
                <input type="radio" name="choice" id="choice {{ rofloop.counter }}" value="{{choice.id}}">
                <!-- forloop.counter indicates how many time the for tag has gone thruogh its loop -->
                <label for="choice {{ forloop.counter }}">
                    {{ choice.choice_text }}
                </label>
                <br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Vote">
    </form>
</body>
</html>

mysite/pollsApp/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Templates Polls Index</title>
</head>
<body>
    {% load static %} 
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    {% if latest_question_list %}
        <ul>
            {% for question in latest_question_list %}
                <li>
                    <a href="{% url 'pollsApp:details' question.id %}">
                        <h3>{{ question.question_text }}</h3>
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>
            No polls are available.
        </p>
    {% endif %}    
</body>
</html>

mysite/pollsApp/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Templates Polls Results</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>
    <ul>
            {% for choice in question.choice_set.all %} 
            <li>
                {{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}
            </li>
            {% endfor %} 
    </ul>

    <a href="{% url 'pollsApp:details' question.id %}">
        Vote again?
    </a>
</body>
</html>